### ISSUE TITLE
Can not create Glint Client in Apache Spark

### ISSUE THREAD

**Issue by mnoumanshahzad** [rjagerman/glint#67]
I am following the instructions on the [Glint Spark Integration page](http://rjagerman.github.io/glint/gettingstarted/spark/). I have a Glint "master" and a "server" running on localhost. I am trying to create a default Glint client in Spark shell and am getting the following error:
`java.lang.NoSuchMethodError: scala.collection.immutable.HashSet$.empty()Lscala/collection/immutable/HashSet;
  at akka.actor.ActorCell$.<init>(ActorCell.scala:336)
  at akka.actor.ActorCell$.<clinit>(ActorCell.scala)
  at akka.actor.RootActorPath.$div(ActorPath.scala:185)
  at akka.actor.LocalActorRefProvider.<init>(ActorRefProvider.scala:465)
  at akka.remote.RemoteActorRefProvider.<init>(RemoteActorRefProvider.scala:124)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
  at scala.util.Try$.apply(Try.scala:192)
  at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
  at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
  at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
  at scala.util.Success.flatMap(Try.scala:231)
  at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
  at akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:585)
  at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:578)
  at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
  at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
  at glint.Client$.start(Client.scala:289)
  at glint.Client$.apply(Client.scala:270)
  at glint.Client$.apply(Client.scala:258)
  ... 48 elided
`
Although in a simple sbt console, I am able to create a Glint client

**Comment by mnoumanshahzad** [comment]
I am getting the same error even if I try initializing the Client object with a Glint Config file

**Comment by MLnick** [comment]
Likely your Scala versions are different between Spark and Glint?

**Comment by mnoumanshahzad** [comment]
Thanks for the help. I was using Scala 2.11 but the Glint Jar was for version Scala 2.10. Although I am still facing a problem with the correct Scala version for everything.
This is what I get when initializing the Client:
`
java.util.concurrent.TimeoutException: Futures timed out after [30000 milliseconds]
  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
  at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
  at scala.concurrent.Await$.result(package.scala:190)
  at glint.Client$.apply(Client.scala:270)
  at glint.Client$.apply(Client.scala:258)
  ... 48 elided
`

And this is seen on the Glint Master's console:
`
[ERROR] [05/26/2017 15:12:16.048] [glint-master-akka.remote.default-remote-dispatcher-5] [Remoting] scala.Option; local class incompatible: stream classdesc serialVersionUID = -114498752079829388, local class serialVersionUID = -2062608324514658839
java.io.InvalidClassException: scala.Option; local class incompatible: stream classdesc serialVersionUID = -114498752079829388, local class serialVersionUID = -2062608324514658839
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1843)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1843)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at akka.serialization.JavaSerializer$$anonfun$1.apply(Serializer.scala:136)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at akka.serialization.JavaSerializer.fromBinary(Serializer.scala:136)
        at akka.serialization.Serialization$$anonfun$deserialize$1.apply(Serialization.scala:104)
        at scala.util.Try$.apply(Try.scala:161)
        at akka.serialization.Serialization.deserialize(Serialization.scala:98)
        at akka.remote.serialization.MessageContainerSerializer.fromBinary(MessageContainerSerializer.scala:63)
        at akka.serialization.Serialization$$anonfun$deserialize$1.apply(Serialization.scala:104)
        at scala.util.Try$.apply(Try.scala:161)
        at akka.serialization.Serialization.deserialize(Serialization.scala:98)
        at akka.remote.MessageSerializer$.deserialize(MessageSerializer.scala:23)
        at akka.remote.DefaultMessageDispatcher.payload$lzycompute$1(Endpoint.scala:58)
        at akka.remote.DefaultMessageDispatcher.payload$1(Endpoint.scala:58)
        at akka.remote.DefaultMessageDispatcher.dispatch(Endpoint.scala:76)
        at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:967)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:437)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

**Comment by mnoumanshahzad** [comment]
Earlier I had been running master and server using the sbt "run master" command. But by using the scripts in sbin, I was able to make it work.
