### ISSUE TITLE
Akka Actor Error when initializing Glint Client

### ISSUE THREAD

**Issue by mnoumanshahzad** [rjagerman/glint#68]
I am trying this implementation of Glint with Apache Flink. I am rather new to Akka and can not figure out the following error message:

`java.lang.NoSuchMethodError: akka.pattern.AskableActorRef$.$qmark$default$3$extension(Lakka/actor/ActorRef;Ljava/lang/Object;)Lakka/actor/ActorRef;
	at glint.Client.<init>(Client.scala:40)
	at glint.Client$$anonfun$start$1.apply(Client.scala:302)
	at glint.Client$$anonfun$start$1.apply(Client.scala:300)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

This message appears simply when I try to create a client ( i.e val gc = Client() )
Is it possible that this message is caused because Apache Flink uses a different version of Akka that Glint and somehow Glint is using the Akka version that Apache Flink has imported? If so, how can I ensure that the right version of Akka is called for Glint and Apache Flink respectively?

Thanks

**Comment by MLnick** [comment]
Likely a version conflict - either scala version or akka. If akka then
unless Flink has a way to manage classpath loading then you can try shading
your akka dependency

**Comment by mnoumanshahzad** [comment]
Thanks alot for a speedy reply. Could you also point out the preferred versions of Scala, SBT and Akka for Glint?
I figured out the following from the build.sbt for Glint
Scala Version = 2.10.6 or 2.11.8
SBT Version = I am using 0.13.15 and it works fine.
Akka Version = 2.3.15 (for Scala 2.10) and 2.4.12 (for Scala 2.4.12)
